name: cas_business_solutions
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  form_builder_validators: ^11.0.0
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3


  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/foreground_logo.png"
  


flutter:


  uses-material-design: true

  assets:
    - assets/images/


flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart


